#50 닉네임 중복 api 연결
mash-up-kr/ssam-d-Android pull request #122
Opened 2023-07-08 03:26 UTC by sooziini

## 작업 내역

-  닉네임 중복 data/domain/presentation layer 구현 및 api 연결

## To. Reviewer

- 중복 에러 상태 코드 받아오는 방법에서 가이드 준 대로 throw Exception("response.statusCode") 이런 형태로 해봤는데.. 이 exception message가 제대로 전달이 안되더라고..? 흑흑
- 그래서 repository에서 HttpException code() 가져와서 ConflictException인지 아닌지 판별하고 에러 던지는 형태로 했어 이 로직을 repository에서 안 하고 ConfliceException class도 만들지 않고 그냥 viewmodel에서 다 처리할 수 있는데 고민하다가 일단 전자 방법으로 해봤어

## 화면
| 기능     | 화면     |
|--------|--------|
|닉네임 중복 확인||

https://github.com/mash-up-kr/ssam-d-Android/assets/51108983/496f5328-d5e0-4230-a487-1b4f065f8794

## 관련 이슈
close #50

2023-07-08 03:47 UTC, sooziini commented
닉네임 중복 외의 에러가 발생했을 경우 어떻게 처리할 것인지 논의 및 추가 필요
edittext 아래에 "중복된 닉네임이에요!" 말고 다른 string을 보여줄 것인지 등등..

2023-07-11 18:41 UTC, JaesungLeee requested changes
수고했엉~~ 몇개 코멘트 달아놨구 나머지 궁금한 부분들 몇개 있긴한데 이거는 내일 이야기 해보장~

2023-07-11 18:41 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +
runCatching으로 줄일 수 있을 것 같은데~?

2023-07-11 18:41 UTC, JaesungLeee commented on domain/src/main/java/com/mashup/domain/usecase/CheckNicknameDuplicationUseCase.kt
> +class ConflictException(message: String) : Exception(message)
별도의 Exception을 만들어놓은 이유가 있을까?

2023-07-11 18:41 UTC, JaesungLeee commented on presentation/src/main/java/com/mashup/presentation/login/LoginScreen.kt
> +    val nicknameState by loginViewModel.nicknameState.collectAsState()
`collectAsStateWithLifecycle`이라는 API 확인해보면 좋을 것 같아!!

2023-07-11 18:41 UTC, JaesungLeee commented on presentation/src/main/java/com/mashup/presentation/login/LoginScreen.kt
>  ) {
나중에 네비게이션 적용하기 수월하게 LoginRoute 하나 추가해놓는 거 어때?? 지금 상황에서는 LoginActivity에서 LoginRoute로 연결되면 될 것 같아~

2023-07-12 11:25 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginScreen.kt
> +    val nicknameState by loginViewModel.nicknameState.collectAsState()
요거는 develop 머지되면 하려했어서 rebase 하고 추가하겠음~

2023-07-12 11:26 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginScreen.kt
>  ) {
오케 사실 login/onboarding/home 각각 activity 하나씩 가지고 있으면 login은 screen이 하나밖에 없어서 route가 과연 필요할 것인가.. 를 혼자 생각하다가 안 넣었는데 일단 넣어둘게 ~

2023-07-12 11:48 UTC, sooziini commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +
그러고 싶었는데.. runCatching으로 409 or else를 판별할 방법을 찾지 못했어 그래서 ConflictException이라는 클래스를 하나 추가한건데 음 이따 자세히 말해줄게 !!

2023-07-13 12:59 UTC, closed without merging