#44 로그인 api 연결
mash-up-kr/ssam-d-Android pull request #97
Opened 2023-06-29 03:36 UTC by sooziini

## 작업 내역

- login api 연결

## To. Reviewer

- 카카오 로그인 사용자 정보로 login api 보내고 성공했다는 로그 확인 완료
- 다른 api 보낼 때 header에 access token이 정상적으로 세팅되는지 확인 필요
    - nickname api로 확인 예정

## 관련 이슈
close #44

2023-06-29 03:37 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +    private fun login(email: String?, socialId: String, deviceToken: String? = "") {
일단 deviceToken은 "" 처리했는데 이 부분도 업데이트 할 예정임다

2023-06-29 05:33 UTC, Huijiny requested changes

2023-06-29 05:33 UTC, Huijiny commented on data/src/main/java/com/mashup/data/network/AppHeaderProvider.kt
> +    @ApplicationContext private val context: Context
땡큐 💖

2023-06-29 05:33 UTC, Huijiny commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +    private val appHeaderProvider: AppHeaderProvider
appHeaderProvider는 좀 더 상위 레이어인 RemoteLoginDataSource내에서 처리하는게 어때? :> 만약 localLoginDataSource가 추가된다 하면
appHeaderPRovider는 remote에서만 사용되는 애니까!

2023-06-29 05:33 UTC, Huijiny commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
요기랑 RequestBody Json 파서 안붙여도되나? moshi!

2023-06-29 05:33 UTC, Huijiny commented on domain/src/main/java/com/mashup/domain/usecase/LoginUseCase.kt
> +data class LoginParam(
오 맞아! 이런식으로 Param 사용하면 돼!

2023-06-29 05:33 UTC, Huijiny commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +                    Timber.i("삐빅- 로그인 실패")
ㅃㅣ빅? 좀 귀엽네

2023-06-29 05:33 UTC, Huijiny commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +                   addPage()
addPage라는 이름은 페이지를 추가한다라는거같은데 로그인되면 어떤페이지가 추가되는걸깡?

2023-06-29 05:33 UTC, Huijiny commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +    private fun addPage() = currentPage++
page관리할때 혹시 maxPage까지 가거나 minimumPage까지 가면 어떻게 처리돼? indexexception같은게 날 수도 있을것같은데 

kotlin에 https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/coerce-in.html coerceIn 이런게 있는데 경계값을 설정해두고 경계값 안에있으면 안에 있는 데이터 반환하고 넘어가면 경계값을 반환해주는거얌. 요런것도 참고해서 방어코드만들어두면 좋을거같아!

2023-06-29 07:22 UTC, JaesungLeee requested changes
수고했얼~

2023-06-29 07:22 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/network/AppHeaderProvider.kt
> +        preferences.edit().putString(JWT, token).apply()
👍

2023-06-29 07:22 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +    private val appHeaderProvider: AppHeaderProvider
난 좀 다른 의견으로, Preference에서 토큰을 set, get하는건 결국에 로컬에서 토큰을 관리하는건데
appHeaderProvider는 우리 사용하고있는 Interceptor에서 사용하게 하고, Repository에서는 LocalDataSource를 통해서 토큰을 save하는 건 어떨까?

2023-06-29 07:22 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
붙어야되는걸로 알고있어 나두

2023-06-29 07:22 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
그리구 이건 같이 확인해봐야 할 거같은데, 나도 Moshi를 처음 써봐서 자료를 좀 찾아보니까
```suggestion
@JsonClass(generateAdapter=true)
data class LoginResponseBody()
```
요런식으로 Annotation 추가를 해주어야 직렬화랑 역직렬화가 되는 것 같거든. 
그렇다면 이 Annotation은 Response에도 추가가 되어야할 것 같아!! 우리 Response에는 이게 안붙어있는 것 같더라구

추가로, `@field:Json(name="~")`랑 `@Json(name="~")`의 차이도 궁금합니당
이 PR에서 다룰 내용은 아니지만 수정이 필요하다하면 하는 김에 Response도 같이 수정해도 될 것 같아서!!

ref. https://kotlinworld.com/117

2023-06-30 07:41 UTC, sooziini commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +    private val appHeaderProvider: AppHeaderProvider
흠 그러면 재성스 의견처럼 LocalLoginDataSource 생성하고 토큰 save 함수 추가하고 Repository에서는 appHeaderProvider가 아니라 localLoginDataSource 사용하는 건 어때!! 희진언니 의견처럼 data source 쪽에서 처리하는 게 좋을 거 같기도 하고 추후에 SharedPreferences에서 DataStore로 마이그레이션 하기로 했으니까 미리 LocalLoginDataSource 만들고 사용하는 게 나을듯해

2023-06-30 09:23 UTC, sooziini commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
2788e5fc38b646db9ce66560777031dd2712a3f3 3f1b0f0d9341e4279928e1b6b3aa3dc74781f572
generateAdapter를 하려면 build.gradle에 moshi codegen을 추가해야 하더라고! 추가하고 generateAdapter 세팅 완 .
https://github.com/square/moshi#codegen

@field:Json(name="~")랑 @Json(name="~")의 차이는..
https://stackoverflow.com/questions/56976656/moshi-in-kotlin-json-vs-fieldjson 이거를 읽어보긴 했는데 사실 잘 와닿진 않더라고..?

2023-06-30 09:47 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +    private fun addPage() = currentPage++
back은 0일 때랑 아닐때 구분해서 처리하고 있고 add는 마지막 페이지인 LoginCompletionScreen에서는 add 하는 코드가 없어서 괜찮다고 생각했어..! 그래서 처리를 따로 안 했는데 coerceIn 함 참고해볼게 고마웡ㅎㅎ
back 버튼 코드: https://github.com/mash-up-kr/ssam-d-Android/blob/develop/presentation/src/main/java/com/mashup/presentation/login/LoginScreen.kt#L46

2023-06-30 09:50 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +                   addPage()
음 LoginScreen이 pager로 3개 screen을 들고 있어서 한 page 넘어가게 할 때 addPage를 사용해 이름을 좀 바꿔볼까 ㅋㅋㅋㅋ`goToNextPage` `backToPrevPage`

2023-06-30 10:23 UTC, JaesungLeee commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
> Serialization does not happen properly when I use @Json in the fields but it started working after changing to @field:Json.

일단 @Json만 있으면 직렬화가 잘 안되었다는데 바꿔보는건 어떠신지~

2023-06-30 10:24 UTC, sooziini commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +    private val appHeaderProvider: AppHeaderProvider
62298bb0f1d71e2947401bffcbc0eea10fc79929
하다보니까 마음이 좀 바껴서 ㅎ.. LocalLoginDataStore 생성하고 그 안에서 희진언니 말처럼 appHeaderProvider 사용하도록 했슴다

2023-06-30 11:05 UTC, sooziini commented on data/src/main/java/com/mashup/data/source/remote/dto/responsebody/LoginResponseBody.kt
> +data class LoginResponseBody(
접수~ ca167e58edc62eb5ddd961edd5f85ecbc1f670e3

2023-06-30 11:08 UTC, sooziini commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +                   addPage()
46671217057635c2f994a6e9478fa4f07485a481

2023-06-30 11:08 UTC, Huijiny commented on data/src/main/java/com/mashup/data/repository/LoginRepositoryImpl.kt
> +    private val appHeaderProvider: AppHeaderProvider
리뷰 참고해줘서 고마워요~~

2023-06-30 11:09 UTC, Huijiny commented on presentation/src/main/java/com/mashup/presentation/login/LoginViewModel.kt
> +                   addPage()
웅 그게 훨씬 더 페이지전환에 관한 이름같당

2023-06-30 11:14 UTC, Huijiny approved these changes

2023-06-30 15:10 UTC, JaesungLeee approved these changes

2023-06-30 15:19 UTC, merged